### PR TITLE
Replace ansible_local.init with ansible_service_mgr default fact.

### PR DESCRIPTION
**Pull request by ipr-cnrs**
It's solved #35 and seems to work fine for me.

### CODE REVIEW

**Comment by drybjed** [comment]
You can drop the check for `ansible_local` compeletely in this case.

**Comment by drybjed** [comment]
Also, can you switch the other tasks in this role that rely on `ansible_local.init` (if there are any)? It could be done in one PR.

**Comment by ipr-cnrs** [comment]
Okay, i will remove `ansible_local` checks :)

**Comment by ipr-cnrs** [comment]
Looks good for me.

**Pull request merged**
